[plugin]
package = "eventyay-paypal"
modules = [ "eventyay_paypal" ]
marketplace_name = "paypal"
pypi = true
repository_servers = { origin = "github.com" }
tag_targets = [ "origin" ]
branch_targets = [ "origin/master" ]
